### ISSUE TITLE
Ошибка подключения библиотек

### ISSUE THREAD

**Issue by a-perminov** [arkuznetsov/cpdb#17]
Пытаюсь использовать cpdb в своем скрипте, получаю ошибку

> {Модуль D:\Programs\OneScript\lib\cpdb\src\Модули\ЗапускПриложений.os / Ошибка в строке: 85 / Неизвестный символ: ЧтениеПараметров}
Процесс терминала завершен с кодом выхода: 1

Это модуль из readparams. В cpdb.os он подключается, но почему-то не находится в зоне видимости ЗапускПриложений.os. 
Если в ЗапускПриложений.os добавить
 `#Использовать readparams`
то скрипт отрабатывает нормально.

Ситуация воспроизводится на 2-х машинах. Устанавливал oscript через инсталлер и из архива - разницы нет.
Некоторые листинги консоли

> d:\Programs\OneScript\lib\cpdb\src>opm list
Пакеты в системном каталоге библиотек <D:\Programs\OneScript\lib>:
1commands@1.2.1
1testrunner@1.5.0
asserts@0.3.1
cmdline@0.6.1
cpdb@0.3.5
delegate@0.1.2
fs@0.4.1
gitrunner@1.5.0
gitsync@2.3.0
json@0.2.1
logos@0.6.2
opm@0.12.1
ReadParams@0.2.0
strings@0.4.1
tempfiles@0.2.1
tool1cd@0.4
v8runner@0.11.2
v8unpack@1.0.1
yadisk@1.0

> d:\Programs\OneScript\lib\cpdb\src>oscript cpdb.os
ОШИБКА - Некорректные аргументы командной строки
Возможные команды:
 help         - Вывод справки по параметрам
...вырезано.....
 merge        - Восстановить файл из частей (требуется установленный 7-zip)
Для подсказки по конкретной команде наберите help <команда>

> d:\Programs\OneScript\lib\cpdb\src>oscript
1Script Execution Engine. Version 1.0.18.101

Сам скрипт 
[test.txt](https://github.com/arkuznetsov/cpdb/files/1469811/test.txt)

ЗЫ: я не до конца уверен, что это ошибка в библиотеке, возможно проблема в самом oscript.

**Comment by arkuznetsov** [comment]
А ошибка возникает при вызове без параметров или для какой-то команды?
Каким образом пытаетесь использовать в своем скрипте? Как библиотеку? Скрипт oscript?

**Comment by a-perminov** [comment]
> А ошибка возникает при вызове без параметров или для какой-то команды?
если выполнить 
> cpdb.os help
то все нормально - см листинге в первом посте

> Каким образом пытаетесь использовать в своем скрипте? Как библиотеку? Скрипт oscript?
Как библиотеку на языке 1Script через дерективу 
#Использовать cpdb
Выполняю скрипт(см приложенный выше файл test.txt, переименовал из .os - не пропускает сайт) - он не проходит проверку - после запуска сразу выдает ошибку, описанную выше

**Comment by arkuznetsov** [comment]
Ясно, не предполагал использование в качестве библиотеки, соответственно не тестировалось. Скорее всего проблема в том, что #Использовать подключает каталог, а не саму библиотеку, и каждый из файлов скриптов подключает по отдельности, т.е. файлы скриптов друг о друге не знают в таком случае.
