### ISSUE TITLE
Дифференциальный бакап

### ISSUE THREAD

**Issue by milanse** [arkuznetsov/cpdb#21]
Хочу использовать возможность делать бакапы из командной строки.
Можно ли добавить ключ -differential по нему дописывать разницу в предыдущий файл ?

declare @backupfile as Varchar(255)

SELECT TOP 1 @backupfile=mf.physical_device_name from msdb..backupset bk      
join msdb..backupmediafamily mf on bk.media_set_id = mf.media_set_id   
where database_name=N'dbname' and bk.type='D' order by  
backup_set_id desc
select @backupfile
BACKUP DATABASE [dbname] TO  DISK = @backupfile WITH  DIFFERENTIAL , NOFORMAT, NOINIT,  NAME = N'Differential Database Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10

**Comment by arkuznetsov** [comment]
Могу рекомендовать взять поковырять модуль ИнструментыСУБД.os там в принципе все прозрачно.
Пока, на мой взгляд, задача несколько не совпадает с целями скрипта.  Если придумаю как идеологически правильно встроить, то добавлю, но быстро не обещаю.

**Comment by milanse** [comment]
ОК, попробую ковырнуть.

**Comment by arkuznetsov** [comment]
Там внутри все через sqlcmd выполняется, так что для вашей задачи в принципе и bat-ника может быть достаточно.
