### ISSUE TITLE
команда putyadisk

### ISSUE THREAD

**Issue by pallid** [arkuznetsov/cpdb#23]
При загрузке ответ от сервиса 

> Яндекс.Диск ответил кодом ошибки 409: Specified path "/tests/testfolder" points to existent directory.
 
```cpdb putyadisk -file "C:/tests/testfolder/testfile.txt" -ya-token XXX -ya-path "C:/tests/testfolder/"```

после чего файл был загружен

**Comment by arkuznetsov** [comment]
В параметре -ya-path нужно указывать путь на самом яндекс-диске, т.е., Например, /tests/testfolder, "C:" - там лишняя.

**Comment by pallid** [comment]
@arkuznetsov да, ошибся, в описании не правильно написал

`/tests/testfolder/`
