### ISSUE TITLE
Создание серверной базы из .dt

### ISSUE THREAD

**Issue by milanse** [arkuznetsov/cpdb#28]
createib
![image](https://user-images.githubusercontent.com/15941393/66112093-e175d700-e5d2-11e9-82a2-a956122d7d59.png)

1. Базу создает, не загружает в нее dt.

2. Разрешить выдачу лицензий сервером в свойствах созданной базы стоит = Нет

**Comment by arkuznetsov** [comment]
@milanse Ошибка загрузки базы из шаблона поправлена.
Флаг включения раздачи лицензий сервером добавлен, но для того чтобы он сработал нужны исправления в v8runner, на что сделан PR (https://github.com/oscript-library/v8runner/pull/101).
Новая версия cpdb, опубликованf в хабе.

**Comment by milanse** [comment]
Круто ) Вот это оперативность, пока я начал думать как сделать PR в раннер, уже все готово )

А как обновляется библиотека пактов OPM ? Автоматом из master ?

**Comment by arkuznetsov** [comment]
@milanse Пока ручками opm push.
