### ISSUE TITLE
Чтение параметров из json-файла

### ISSUE THREAD

**Issue by JohnyDeath** [arkuznetsov/cpdb#3]
Можно ли прикрутить чтение параметров из json-файла?
https://github.com/Stepa86/ReadParams

**Comment by arkuznetsov** [comment]
Со временем, сейчас пока предполагается использование из-под jenkins.

**Comment by arkuznetsov** [comment]
Кстати вопрос, а в каких библиотеках (желательно основанных на app-template) сейчас можно подсмотреть использование ReadParams? Так сказать набраться опыта.

**Comment by JohnyDeath** [comment]
У того же Степана есть: https://github.com/Stepa86/1C-Deploy-and-CopyDB

**Comment by arkuznetsov** [comment]
Сделано, пока в develop.
