### ISSUE TITLE
Расширить команду compress - получать список несжатых таблиц и индексов

### ISSUE THREAD

**Issue by yuriybylinkin** [arkuznetsov/cpdb#37]
Если мы не внедряем в базу SQL дополнительные триггеры, то после изменения метаданных, влекущих за собой изменение структуры таблиц, в базе оказываются несжатые таблицы и индексы из-за реструктуризации.
Например - добавили реквизит в табличную часть Товары Заказа клиента - база резко распухла.
Хочется видеть,  какие таблицы не сжаты.
Соответственно при сжатии делать ребилд только несжатых таблиц и индексов.

**Comment by yuriybylinkin** [comment]
ТекстЗапроса = "
	|USE [%1]
	|SELECT 
	|sp.object_id as object_id,
	|st.name AS tablename, 
	|INDX.name AS indexname, 
	|sp.data_compression AS type	
	|FROM sys.partitions SP
	|INNER JOIN sys.tables ST	
	|	ON st.object_id = sp.object_id
	|LEFT JOIN sys.indexes INDX
	|	ON INDX.object_id = ST.object_id
	|		AND INDX.index_id = SP.index_id
	|	order BY type
	|";
	
	ТекстЗапроса = СтрШаблон(ТекстЗапроса, ИмяБазы);

**Comment by arkuznetsov** [comment]
@yuriybylinkin Сейчас compress просто жмет несжатые таблицы и индексы. Не совсем понятно зачем ее расширять, вроде выполняет то что задумано.
Может другую команду добавить или воспользоваться командой script.
Тут в ближайшее время переход на cli ожидается, т.е. глобальный рефакторинг :-)
