### ISSUE TITLE
Добавить логи в сценарии

### ISSUE THREAD

**Issue by dudkitt** [arkuznetsov/cpdb#49]
Для удобства диагностики желательно добавить в сценарии  возможность записи простых текстовых логов вида:
Шаг: "Копирование базы" начат 11:20 
Шаг: "Копирование базы" закончен 11:30 
и т.п.
Сейчас приходится cpdb в другие скрипты заворачивать.

**Comment by arkuznetsov** [comment]
Не совсем понял чего не хватает, вроде как все действия обернуты в логи вида "Начало..." - "Конец..."?

**Comment by dudkitt** [comment]
> Не совсем понял чего не хватает, вроде как все действия обернуты в логи вида "Начало..." - "Конец..."?

Чтобы писало в текстовый лог заданный в сценарии, а не в stdout

**Comment by arkuznetsov** [comment]
Тут https://github.com/oscript-library/logos есть примеры настройки логирования.

Например:

```bat
set LOGOS_CONFIG=logger.oscript.app.cpdb=INFO, cpdbdebug, console;appender.cpdbdebug=ВыводЛогаВФайл;appender.cpdbdebug.level=DEBUG;appender.cpdbdebug.file=d:\repo\cpdb\cpdb-debug.log;appender.console=ВыводЛогаВКонсоль;appender.console.level=INFO
```

настраивает вывод лога в файл `d:\repo\cpdb\cpdb-debug.log` с уровнем DEBUG и в stdout с уровнем INFO.
